### ISSUE TITLE
Missing const/let declaration?

### ISSUE THREAD

**Issue by waldothedeveloper** [philnash/bulk-sms-alerts#2]
Hi, Phil, it's me with another doubt :)

When I look at the file 99flake.js line 14: 
[click-here-to-go-to-line](https://github.com/philnash/bulk-sms-alerts/blame/master/99flake.js#L14)

is the code ```notification  = service.notifications```
missing a const or let declaration? 

I don't see it imported or declared previously...

Best and thank you for such great articles!

**Comment by philnash** [comment]
Hey @waldothedeveloper, you've got me here! It should have a `const` or `let` but in fact I've accidentally defined a global variable (which is why it still works).

Further to that, since we never use the promise that is returned from `service.notifications.create` we never needed to save it to a variable either. So I will remove `notification = ` from this code and it will be better.

**Comment by philnash** [comment]
I've updated this in the [blog post too](https://www.twilio.com/blog/2017/12/send-bulk-sms-twilio-node-js.html). Thanks!

**Comment by waldothedeveloper** [comment]
Phil how're you!! 
I've been busy today haven't been able to answer you.
I'll be sending you an email with what I want to do with Twilio and AWS Amplify.
Thanks again for your amazing help.
